### ISSUE TITLE
反射的获取Class对象方法一应该是类字面常量

### ISSUE THREAD

**Issue by fullstcat** [dota-st/JavaSec#2]
类字面常量是编译器在编译时生成的常量值。在编译时，类字面常量被解析为指向相应 Class 对象的引用，这个引用被存储在编译后的字节码文件中。在运行时，这个常量值被加载到内存中，并被视为一个常量，它不会被修改或改变其值。

**Comment by dota-st** [comment]
感谢纠正，已更新
